version: '3.3'

services:
  drupal:
    image: drupal:latest
    networks:
      - drupal
    ports:
      - 80:80
      - 443:443
    volumes:
      - drupal-data:/var/www/html
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - drupal
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./db:/var/lib/mysql:rw

  certbot:
    depends_on:
      - drupal
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - drupal-data:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email administration@tech.market --agree-tos --no-eff-email --staging -d tech.market -d www.tech.market



networks:
    drupal:
volumes:
  drupal-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$PWD/drupal'
  db-data:
  certbot-etc:
